function Hd = FreqFilt_Alpha
%FreqFilt_Alpha Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 14-Aug-2016 16:16:15

% FIR least-squares Bandpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 128;  % Sampling Frequency

N      = 48;    % Order
Fstop1 = 7.5;   % First Stopband Frequency
Fpass1 = 8;     % First Passband Frequency
Fpass2 = 12;    % Second Passband Frequency
Fstop2 = 12.5;  % Second Stopband Frequency
Wstop1 = 1;     % First Stopband Weight
Wpass  = 1;     % Passband Weight
Wstop2 = 1;     % Second Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2]);
Hd = dfilt.dffir(b);

% [EOF]
