function [TS,AF3,T7,PZ,T8,AF4] = ImportBaseline(filename, startRow, endRow)
%ImportBaseline Import numeric data from a text file as column vectors.
%   [TS,AF3,T7,Pz,T8,AF4] = ImportBaseline(FILENAME) Reads data from
%   text file FILENAME for the default selection.
%
%   [TS,AF3,T7,Pz,T8,AF4] = ImportBaseline(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [TS,AF3,T7,Pz,T8,AF4] = ImportBaselinehea('JULES_baseline_20160808-124059.csv',2, 15353);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/08/14 20:25:17

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
TS = dataArray{:, 1};
AF3 = dataArray{:, 2};
T7 = dataArray{:, 3};
PZ = dataArray{:, 4};
T8 = dataArray{:, 5};
AF4 = dataArray{:, 6};


